// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeCIZ2nMbdVmtXg4xwyJv04CXBuWAY27c',
    appId: '1:4504492892:web:ae48ad261442a370be3f99',
    messagingSenderId: '4504492892',
    projectId: 'biberberapp-ea2bd',
    authDomain: 'biberberapp-ea2bd.firebaseapp.com',
    storageBucket: 'biberberapp-ea2bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLKBeuJ0BJbSKjV5eYhKQl_tyGTDGwPBA',
    appId: '1:4504492892:android:4b198fd5de59ac92be3f99',
    messagingSenderId: '4504492892',
    projectId: 'biberberapp-ea2bd',
    storageBucket: 'biberberapp-ea2bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHgMTx0hKNvIFYY-90De6BChJ81-l5sqk',
    appId: '1:4504492892:ios:4107aa429c95defbbe3f99',
    messagingSenderId: '4504492892',
    projectId: 'biberberapp-ea2bd',
    storageBucket: 'biberberapp-ea2bd.appspot.com',
    iosClientId:
        '4504492892-bggr3698ait9bovilohtosh5o5km2rac.apps.googleusercontent.com',
    iosBundleId: 'com.example.biberberapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHgMTx0hKNvIFYY-90De6BChJ81-l5sqk',
    appId: '1:4504492892:ios:4107aa429c95defbbe3f99',
    messagingSenderId: '4504492892',
    projectId: 'biberberapp-ea2bd',
    storageBucket: 'biberberapp-ea2bd.appspot.com',
    iosClientId:
        '4504492892-bggr3698ait9bovilohtosh5o5km2rac.apps.googleusercontent.com',
    iosBundleId: 'com.example.biberberapp',
  );
}
